//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrganisationEditing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewCreation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReviewCreation()
        {
            this.ReviewAssignments = new HashSet<ReviewAssignment>();
            this.ReviewSubmissions = new HashSet<ReviewSubmission>();
        }
    
        public int ReviewId { get; set; }
        public string Agenda { get; set; }
        public System.DateTime Review_Cycle_Start_Date { get; set; }
        public System.DateTime Review_Cycle_End_Date { get; set; }
        public string MinimunRating { get; set; }
        public string MaximumRating { get; set; }
        public string Description { get; set; }
        public int Id { get; set; }
        public System.DateTime Created_On { get; set; }
        public string Created_by { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReviewAssignment> ReviewAssignments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReviewSubmission> ReviewSubmissions { get; set; }
    }
}
