//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrganisationEditing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewSubmission
    {
        public int ReviewId { get; set; }
        public int EmployeeId { get; set; }
        public string Rating { get; set; }
        public string Feedback { get; set; }
        public int id { get; set; }
        public int ReviewerId { get; set; }
        public System.DateTime Created_On { get; set; }
        public string Created_by { get; set; }
        public Nullable<int> OrganisationIdF { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ReviewCreation ReviewCreation { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
